In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu124


## Introduction to Tensors
### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [2]:
# scalar
scalar = torch.tensor(3.14159)
print(scalar)

tensor(3.1416)


In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python Int
scalar.item()

3.141590118408203

In [10]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])
vector

tensor([1, 2, 3, 4, 5])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([5])

In [19]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
# ndim counts the number of dimensions, or just see the amount of []
MATRIX.ndim

2

In [22]:
MATRIX.shape

torch.Size([3, 3])

In [25]:
MATRIX[0]

tensor([1, 2, 3])

In [31]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 4, 3])

It says tensor has 1, 4 by 3 matrix

Matrix and Tensor are writeen with Capital letter, and vector is written with small letter

### Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [54]:
# Create a random tensor of size (3, 3)
random_tensor = torch.rand( 3, 3)
random_tensor

tensor([[0.8508, 0.7727, 0.6045],
        [0.3067, 0.7086, 0.5108],
        [0.0267, 0.3074, 0.1477]])

In [44]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor=torch.rand(3, 224, 224) # Height, Width, Channels RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Challenge

In [50]:
another_random_tensor = torch.rand (size=(10,512,512))
another_random_tensor.shape, another_random_tensor.ndim

(torch.Size([10, 512, 512]), 3)

### Zeros and Ones Tensor

In [52]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [55]:
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [58]:
# Create Tensors of all ones
ones = torch.ones(size=(3, 3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [63]:
# Use torch.arange to create a tensor with values starting from start up to end with a step size of step
one_to_ten=torch.arange(1, 12,2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11])

In [64]:
# Creating Tensors Like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [70]:
# Float 32 Tensor
# Important Parameters dtype, device, requires_grad
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What data type is the tensor 
                               device="cuda", # Can be "cpu" or "cuda" (GPU)
                               requires_grad=False) # Whether or not to track the gradient of the tensor
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0'), torch.float32)

In [71]:
# Convert float_32_tensor to float16
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16), torch.float16)

In [73]:
result_float_16_and_32 = float_16_tensor * float_32_tensor
result_float_16_and_32, result_float_16_and_32.dtype

(tensor([ 9., 36., 81.], device='cuda:0'), torch.float32)